#if !canImport(ObjectiveC)
import XCTest

extension PlaceholderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PlaceholderTests = [
        ("test_Placeholder", test_Placeholder),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PlaceholderTests.__allTests__PlaceholderTests),
    ]
}
#endif
